### ISSUE TITLE
Update the SDK setup guide

### ISSUE THREAD

**Issue by brightblade** [circuitdojo/nrf9160-feather-examples-and-drivers#10]
Just got my board, a few issues I've noticed with the setup guide
1. The SDK setup guide(@docs.jaredwolff.com) for all OSs states to run Zephyr Tools: Init Repo with the GIT repo URL but the documentation doesn't state which branch to choose.  In VS Code, the Zephyr tool prompts the branch with the message "Press enter for default", so I hit enter and got an error saying the branch doesn't exist:

```
=== Initializing in C:\Users\brigh\Desktop\David\GpsTracker\Test
--- Cloning manifest repository from https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers.git, rev. west.yml
Cloning into 'C:\Users\brigh\Desktop\David\GpsTracker\Test\.west\manifest-tmp'...
**fatal: Remote branch west.yml not found in upstream origin**
FATAL ERROR: command exited with status 128: git clone --branch west.yml https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers.git 'C:\Users\brigh\Desktop\David\GpsTracker\Test\.west\manifest-tmp'
```

I don't know much about the west tool / manifest if you can configure a default branch, otherwise I'd recommend stating in the documentation which branch the user should checkout.  I then checked out the "main" branch which led to a whole bunch of new problems....eventually I found "v1.7.x" branch to have most samples compiling successfully.

2nd issue:
The "v1.7.x" and "v1.9.x" branches README.md have a DIFFERENT URL and therefore returns another error.
The URL is:
git@github.com:circuitdojo/nrf9160-feather-examples-and-drivers.git

The error:

```
_Cloning into 'C:\Users\brigh\Desktop\David\GpsTracker\Test\.west\manifest-tmp'...
git@github.com: Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists._

```
I feel the solution would be to use the working URL from the docs website instead of a default github user in the URL.

3rd issue:
The SDK setup guide(@docs.jaredwolff.com) for all 3 OSs show the **incorrect** build tool name as: **Zephyr Tools: Load**
The README.md has the correct tool name as: **Zephyr Tools: Load via Bootloader**

I did update the README.md and attached it for the first two issues:

[README.md](https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers/files/9125353/README.md)

**Comment by jaredwolff** [comment]
> The SDK setup guide(@docs.jaredwolff.com) for all OSs states to run Zephyr Tools: Init Repo with the GIT repo URL but the documentation doesn't state which branch to choose. In VS Code, the Zephyr tool prompts the branch with the message "Press enter for default", so I hit enter and got an error saying the branch doesn't exist:

May have caught the SDK/repository in flux. The default option works now. 👍 

 > The "v1.7.x" and "v1.9.x" branches README.md have a DIFFERENT URL and therefore returns another error.

This is fixed. Thanks for catching it!

> The SDK setup guide(@docs.jaredwolff.com) for all 3 OSs show the incorrect build tool name as: Zephyr Tools: Load
> The README.md has the correct tool name as: Zephyr Tools: Load via Bootloader

Ahh ok. I changed it to be more clear!

Thanks for the feedback @brightblade. Next time tag me or email me directly. I don't always get notifications about issues..
