### ISSUE TITLE
Unable to build bootloader

### ISSUE THREAD

**Issue by mjm987** [circuitdojo/nrf9160-feather-examples-and-drivers#14]
After I downloaded via uart using newtmgr a app image with CONFIG_FLASH enabled, the bootloader crashed.

Now I tried to generate a new bootloader image using this repos overlay:
 [of](https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers/blob/v2.4.x/shared/conf/mcuboot/circuitdojo_feather_nrf9160ns.overlay)  

Unfortunately this results in following error:

```
CMake Warning at /opt/zephyrproject/zephyr/CMakeLists.txt:853 (message):
  No SOURCES given to Zephyr library: drivers__spi
  Excluding target from build.
....
undefined reference to `__device_dts_ord_104'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

```

Are there some additional CONFIG_* options needed to successfully build the bootloader image?

Or alternatively where could I dowenload the original bootloader image for the nrf9160 feather v5 module?

**Comment by mjm987** [comment]
Ok, the error above seems to raise because I used the bootloader from the zephyrproject and not from ncs tree.
But when I use the bootloder from ncs tree, I get following error: 


```
warning: The choice symbol MINIMAL_LIBC (defined at lib/libc/Kconfig:61) was selected (set =y), but
PICOLIBC (defined at lib/libc/Kconfig:72) ended up as the choice selection. See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_MINIMAL_LIBC and/or look up MINIMAL_LIBC in
the menuconfig/guiconfig interface. 
....
CMake Error at /opt/ncs/nrf/lib/fprotect/CMakeLists.txt:15 (message):
  No fprotect backend selected.
```
It seems I used a newer NCS or bootloader release possibly because I installed the sdk and tools manually and not via "Circuit Dojo Zephyr SDK Tools" extension?

**Comment by jaredwolff** [comment]
Sorry @mjm987 there's not enough information here to know what exactly is going on. The bootloader should remain unchanged as long as you didn't overwrite it. If you did overwrite it you can write the hex in this folder: https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers/tree/v2.4.x/bin

And it should get you back go square one.

**Comment by jaredwolff** [comment]
Feel free to leave a message on https://community.circuitdojo.com/ for faster support.
