### ISSUE TITLE
printf in accelerometer example does not format

### ISSUE THREAD

**Issue by turbinenreiter** [circuitdojo/nrf9160-feather-examples-and-drivers#4]
See this line: https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers/blob/6e092194f24670328d717681204d1a941e8247b6/samples/accelerometer/src/main.c#L41

The printf outputs the following:

```
#27 @ 25206 ms: x %f , y %f , z %f
```

Expected
```
#27 @ 25206 ms: x 0.0, y 0.0 , z 9.91
```

**Comment by jaredwolff** [comment]
Should be working ok in the v1.7.x branch.
