### ISSUE TITLE
Missing CONFIG_REBOOT Flag Branch v1.7.x in Tracker

### ISSUE THREAD

**Issue by ColeMurray** [circuitdojo/nrf9160-feather-examples-and-drivers#6]
Setup:
- install nfed 1.7.x
- install nrf sdk 1.70

When building the tracker sample, the build fails due to missing reference on sys_reboot.
```
/opt/nordic/ncs/v1.7.0/em-lte-application/applications/tracker/src/main.c:100: undefined reference to `sys_reboot'
/opt/nordic/ncs/v1.7.0/toolchain/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.bfd: /opt/nordic/ncs/v1.7.0/em-lte-application/applications/tracker/src/main.c:89: undefined reference to `sys_reboot'
/opt/nordic/ncs/v1.7.0/toolchain/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.bfd: /opt/nordic/ncs/v1.7.0/em-lte-application/applications/tracker/src/main.c:95: undefined reference to `sys_reboot'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers/blob/v1.7.x/samples/tracker/src/main.c#L90
https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_REBOOT.html

Fix:
Add ```CONFIG_REBOOT=y``` to the prj.conf

**Comment by jaredwolff** [comment]
@ColeMurray thanks for reporting! (and sorry for the delay. I don't monitor the Github issues here) Looks like it's there now.
