### ISSUE TITLE
Update the SDK setup guide

### ISSUE THREAD

**Issue by muffeeee** [circuitdojo/nrf9160-feather-examples-and-drivers#8]
The Windows SDK setup guide (https://docs.jaredwolff.com/nrf9160-sdk-setup-windows.html) is not updated to reflect the current procedure.

I had a hard time loading any sample sketch onto my nrf9160 boards, until I checked out this repo and found that the readme here had a few details that the setup guide left out.

It would probably be nice for other newcomers if the setup guide reflected the changes.

**Comment by jaredwolff** [comment]
@muffeeee I think everything should be up to date now. Let me know if you see any more deficiencies.
